### ISSUE TITLE
PR #910 adds a `user.name` property component to the default `tmpdir` for `SortingCollection`.

### ISSUE THREAD

**Issue by tbl3rd** [samtools/htsjdk#1030]
PR #910 adds a `user.name` property component to the default `tmpdir` for `SortingCollection`.

This change to line 347 of `SortingCollection`.
```
-        final File tmpDir = new File(System.getProperty("java.io.tmpdir"));
+        final Path tmpDir = IOUtil.getDefaultTmpDirPath();
```
adds the value of the `user.name` property as an extra component to the default `tmpdir` for `SortingCollection` if it is not already present.

Furthermore, `SortingCollection.newTempFile()` will now throw unless the `java.io.tmpdir/user.name` temporary directory exists.

```
Caused by: java.nio.file.NoSuchFileException:
  java.io.tmpdir/user.name/sortingcollection.<some-number>.tmp
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.createFile(Files.java:632)
	at java.nio.file.TempFileHelper.create(TempFileHelper.java:138)
	at java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:161)
	at java.nio.file.Files.createTempFile(Files.java:852)
	at htsjdk.samtools.util.IOUtil.newTempPath(IOUtil.java:316)
	at htsjdk.samtools.util.SortingCollection.newTempFile(SortingCollection.java:255)
	at htsjdk.samtools.util.SortingCollection.spillToDisk(SortingCollection.java:220)
	... 8 more
```

The following change would restore the prior behavior while retaining the `java.nio.file.Path` changes.
```
-        final Path tmpDir = IOUtil.getDefaultTmpDirPath();
+        final Path tmpDir = Paths.get(System.getProperty("java.io.tmpdir"));
```

Saw this while running htsjdk 2.13.0 over HotSpot 1.8.0_121-b13 on Red Hat 2.6.32.

**Comment by tbl3rd** [comment]
... for the PR link which doesn't work in the issue title.
