### ISSUE TITLE
IOUtil.getPath fails when the input has spaces.

### ISSUE THREAD

**Issue by lbergelson** [samtools/htsjdk#1034]
`IOUtil.getPath("some file")` explodes:

```
Caused by: java.net.URISyntaxException: Illegal character in path at index 4: some file
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
	at java.net.URI$Parser.parse(URI.java:3063)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	... 25 more
```

This is due to converting it to a URI first.  It should not explode.

**Comment by nh13** [comment]
I also think we should be using the `URI` constructor and not the `URI.create` method after reading the javadoc for the latter.

**Comment by jb-adams** [comment]
I had a look at this yesterday, I think we can get rid of the error if we check that the passed string is a valid URI (has scheme, no illegal characters, etc.) before invoking `URI.create`. If not, then the string is treated as a local filesystem path.

Thoughts?

**Comment by cmnbroad** [comment]
@jb-adams Hi Jeremy -I think you're on the right track. We have developed a more generalized solution for this in a separate repo, and use in GATK,  in the form of an interface and a [concrete type](https://github.com/samtools/htsjdk-next-beta/blob/master/core/src/main/java/org/htsjdk/core/utils/PathSpecifier.java#L81) that handles these conversions. It normalizes all inputs to a URI internally, and also has some other advantages. Integrating that into htsjdk is a much a larger task, but you might look at the implementation for inspiration, and there are also a [boatload](https://github.com/samtools/htsjdk-next-beta/blob/master/core/src/test/java/org/htsjdk/core/utils/PathSpecifierUnitTest.java) of test cases in there.

**Comment by jb-adams** [comment]
Hi @cmnbroad, looks great, I think it would be good to implement something similar in htsjdk. I'm pretty new to developing here, so I was curious, will htsjdk-next-beta replace htsjdk? Which repo are current versions of GATK and Picard using?

**Comment by cmnbroad** [comment]
@jb-adams GATK and Picard both depend on this repo; htsjdk-next doesn't (yet) have a sufficient critical mass of functionality to warrant switching. The URI classes were designed with the idea that they would migrate their way here at some point, but I'd suggest getting maintainer buy-in before spending much time on it.  @lbergelson or @tfenne any thoughts on this ? GATK has its own copy of them, which could be discarded if they lived in htsjdk, and I think it would benefit Picard and possibly other consumers as well.

**Comment by jb-adams** [comment]
@cmnbroad sounds good, I'll wait till we get the go ahead from maintainers, then I can work on this.

**Comment by tfenne** [comment]
Fixed on master for the upcoming 6.0.0 by #1784: `IOUtil.getPath` treats a string that isn't a valid URI (e.g. one containing spaces) as a local path instead of failing.
