### ISSUE TITLE
SAMTextHeaderCodec should not accumulate entire header in StringBuilder

### ISSUE THREAD

**Issue by heuermh** [samtools/htsjdk#1045]
From a thread on our gitter channel

> Also, I should've mention that my BAM is kind of special in the way that there are about 39M contigs (i.e. reference sequences) in the header, it's a result of an alignment against a very fragmented assembly.

To reproduce, I added 1,000,000 @SG records to the header for a 1G BAM file from 1000G
```
17/11/30 13:01:21 ERROR SparkUncaughtExceptionHandler: [Container in shutdown] Uncaught exception in thread Thread[Executor task launch worker for task 2,5,main]
java.lang.OutOfMemoryError: Java heap space
    at java.util.Arrays.copyOf(Arrays.java:3332)
    at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:137)
    at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:121)
    at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:421)
    at java.lang.StringBuilder.append(StringBuilder.java:136)
    at htsjdk.samtools.SAMTextHeaderCodec.advanceLine(SAMTextHeaderCodec.java:139)
    at htsjdk.samtools.SAMTextHeaderCodec.decode(SAMTextHeaderCodec.java:94)
    at htsjdk.samtools.BAMFileReader.readHeader(BAMFileReader.java:667)
    at htsjdk.samtools.BAMFileReader.<init>(BAMFileReader.java:328)
    at htsjdk.samtools.BAMFileReader.<init>(BAMFileReader.java:268)
    at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:317)
    at org.seqdoop.hadoop_bam.BAMRecordReader.createSamReader(BAMRecordReader.java:198)
    at org.seqdoop.hadoop_bam.BAMRecordReader.initialize(BAMRecordReader.java:147)
    at org.apache.spark.rdd.NewHadoopRDD$$anon$1.liftedTree1$1(NewHadoopRDD.scala:182)
    at org.apache.spark.rdd.NewHadoopRDD$$anon$1.<init>(NewHadoopRDD.scala:179)
    at org.apache.spark.rdd.NewHadoopRDD.compute(NewHadoopRDD.scala:134)
    at org.apache.spark.rdd.NewHadoopRDD.compute(NewHadoopRDD.scala:69)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
    at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
    at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
    at org.apache.spark.scheduler.Task.run(Task.scala:108)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

Relevant code at
https://github.com/samtools/htsjdk/blob/master/src/main/java/htsjdk/samtools/SAMTextHeaderCodec.java#L56
https://github.com/samtools/htsjdk/blob/master/src/main/java/htsjdk/samtools/SAMTextHeaderCodec.java#L139

**Comment by yfarjoun** [comment]
In the end the header is being held in memory by the reader. How big the
the header?

**Comment by nh13** [comment]
I think the issue is that we only decide to discard the text harder if it is too large when there are no validation errors.  And determine that after the full header has been read in.

**Comment by pshapiro4broad** [comment]
If someone picks this up, see the comments on closed PR https://github.com/samtools/htsjdk/pull/1046
Especially https://github.com/samtools/htsjdk/pull/1046/files#r154855631

**Comment by tfenne** [comment]
Fixed by #1361 (2.20.0): `SAMTextHeaderCodec` no longer accumulates the header text.
