### ISSUE TITLE
MergingIterator throws ConcurrentModificationException when closing mid-iteration

### ISSUE THREAD

**Issue by cwhelan** [samtools/htsjdk#1055]
`MergingIterator.close` throws a `ConcurrentModificationException` if it is called mid-iteration and it is merging over at least three sub-iterators.

While working on a tool based on GATK's `MultiVariantWalker` (building on htsjdk 2.13.1) that walks over multiple VCF files, I noticed that if my tool threw an exception while processing, instead of printing the application exception, it instead failed with a `java.util.ConcurrentModificationException` and swallowed the application exception. A typical displayed stacktrace is:

```
java.util.ConcurrentModificationException
	at java.util.PriorityQueue$Itr.next(PriorityQueue.java:535)
	at htsjdk.samtools.util.MergingIterator.close(MergingIterator.java:135)
	at org.broadinstitute.hellbender.engine.MultiVariantDataSource.closeOpenIterationIfNecessary(MultiVariantDataSource.java:368)
	at org.broadinstitute.hellbender.engine.MultiVariantDataSource.close(MultiVariantDataSource.java:223)
	at org.broadinstitute.hellbender.engine.MultiVariantWalker.onShutdown(MultiVariantWalker.java:103)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:131)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:185)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:204)
	at org.broadinstitute.hellbender.engine.MultiVariantWalkerIntegrationTest.testWalkerThrowsException(MultiVariantWalkerIntegrationTest.java:272)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
```

I've narrowed this down to a bug in htsjdk's `MergingIterator.close()`. In particular, if `close()` is called while iterating over at least three sub-iterators, a `ConcurrentModificationException` is thrown. 

A test to reproduce this issue which can be added to `MergingIteratorTest` is:

```
	@Test()
	public void testCloseMultipleIteratorsMidIteration() {
		final Queue<Integer> queueOne = new LinkedList<Integer>();
		queueOne.add(1);
		queueOne.add(4);
		queueOne.add(7);

		final Queue<Integer> queueTwo = new LinkedList<Integer>();
		queueTwo.add(2);
		queueTwo.add(5);
		queueTwo.add(8);

		final Queue<Integer> queueThree = new LinkedList<Integer>();
		queueThree.add(3);
		queueThree.add(6);
		queueThree.add(9);

		final Collection<CloseableIterator<Integer>> iterators = new ArrayList<CloseableIterator<Integer>>(3);
		Collections.addAll(
				iterators,
				new QueueBackedIterator<>(queueOne),
				new QueueBackedIterator<>(queueTwo),
				new QueueBackedIterator<>(queueThree));

		final MergingIterator<Integer> mergingIterator = new MergingIterator<Integer>(
				INTEGER_COMPARATOR,
				iterators);

		Assert.assertEquals(mergingIterator.next().intValue(), 1);
		Assert.assertEquals(mergingIterator.next().intValue(), 2);
		Assert.assertEquals(mergingIterator.next().intValue(), 3);

		mergingIterator.close();
		Assert.assertFalse(mergingIterator.hasNext());
	}
```

The issue is that `MergingIterator.close()` calls `remove()` on the collection of iterators itself, rather than using an `iterator.remove()` call.

I will prepare a PR to fix this.

**Comment by lbergelson** [comment]
fixed by #1056
