### ISSUE TITLE
ENA Reference Service tests failing

### ISSUE THREAD

**Issue by lbergelson** [samtools/htsjdk#1080]
The ENA reference service tests are failing and causing all pr's to fail.  It may be a transient (but it's been happening for hours) failure, or we may need to make changes somewhere.

```
EnaRefServiceTest:
- testEnaRefServiceData(57151e6196306db5d9f33133572a5482) *** FAILED ***
  [secure].samtools.cram.ref.EnaRefService$GaveUpException:
  at [secure].samtools.cram.ref.EnaRefService.getSequence(EnaRefService.java:112)
  at [secure].samtools.cram.ref.EnaRefService.getSequence(EnaRefService.java:26)
  at [secure].samtools.cram.ref.EnaRefServiceTest.testEnaRefServiceData(EnaRefServiceTest.java:20)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
  at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
  at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
  ...
- testEnaRefServiceData(0000088cbcebe818eb431d58c908c698) *** FAILED ***
  [secure].samtools.cram.ref.EnaRefService$GaveUpException:
  at [secure].samtools.cram.ref.EnaRefService.getSequence(EnaRefService.java:112)
  at [secure].samtools.cram.ref.EnaRefService.getSequence(EnaRefService.java:26)
  at [secure].samtools.cram.ref.EnaRefServiceTest.testEnaRefServiceData(EnaRefServiceTest.java:20)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
  at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
  at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
  ...
```

We should either fix, disable, or skip the tests.

**Comment by lbergelson** [comment]
And now I reran locally and it just passed.  Seems like I may have opened this ticket just as the problem resolved itself.

**Comment by yfarjoun** [comment]
Can you email them? They were very responsive to me last time.

**Comment by lbergelson** [comment]
I'm not sure the problem is on their end. The tests are passing on my laptop and failing on travis still.

**Comment by lbergelson** [comment]
The problem went away on it's own after a day.  Mysterious.
