### ISSUE TITLE
input streams opened from Paths fail when the underlying file is a pipe

### ISSUE THREAD

**Issue by lbergelson** [samtools/htsjdk#1084]

**Comment by lbergelson** [comment]
We should also file a bug with java.

**Comment by nh13** [comment]
@lbergelson I just hit this issue with when upgrading from 2.13.0 to 2.14.3.  Not supporting `/dev/stdin` as a path is a serious regression causing production issues on my end.  I have confirmed it works with 2.13.0 and now fails (unexpectedly) in 2.14.3: https://github.com/fulcrumgenomics/fgbio/issues/404

**Comment by nh13** [comment]
@tfenne

**Comment by nh13** [comment]
I can also confirm that reading from stdin works in 2.14.1 and not in 2.14.2, with the latter including #1077 and on.

**Comment by lbergelson** [comment]
@nh13 Did reading from Stdin as a path work before?  I was under the impression that it had never worked.  

There's a bug in the java implementation of `Files.newInputStream()` which makes it annoying to work around.
The following 
```
    @Test
    public void testStdin() throws IOException {
        final InputStream inputStream = Files.newInputStream(Paths.get("/dev/stdin/"));
        inputStream.available();
    }
```

```
java.io.IOException: Illegal seek

	at sun.nio.ch.FileChannelImpl.position0(Native Method)
	at sun.nio.ch.FileChannelImpl.position(FileChannelImpl.java:264)
	at sun.nio.ch.ChannelInputStream.available(ChannelInputStream.java:116)
	at htsjdk.samtools.SamReaderFactoryTest.testStdin(SamReaderFactoryTest.java:539)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
```

**Comment by nh13** [comment]
@lbergelson it fails in 2.14.2 and works in 2.14.1: https://github.com/fulcrumgenomics/fgbio/issues/404

**Comment by lbergelson** [comment]
If it worked before it worked with the very nasty caveat that the if you were reading something GZIP'd from a pipe you could have random corruption of the data you were reading.  See https://github.com/broadinstitute/gatk/issues/4224

The issue is that the GzipInputStream uses `available()` to determine end of stream in some cases, which is a misuse of `available()` and a violation of the contract, but it's been unpatched in java for a long time and there's no reason to think it will be fixed in the future.  So if you have a stream that has a default implementation of available() then you risk corrupted data.

**Comment by tfenne** [comment]
@lbergelson The regression we're seeing is when reading BAM specifically, which uses `BlockCompressedInputStream` which is totally independent from `GzipInputStream` - it does it's own stream handling and uses a `BlockGunzipper` to do the decompression.  As @nh13 states, it was definitely working previously.

I think part of the problem is that we have too many code-paths for opening SAM/BAM/CRAM.  Am I right in saying that all `java.io.File`s can be equally well modeled by `java.nio.file.Path`s?  If that's the case perhaps we can eliminate `FileInputResource` in `SamReaderFactory` and have it just build the `Path` equivalent with `file.toPath`?  That would simplify things and highlight problems like this faster.  Thoughts?

**Comment by tfenne** [comment]
Also, if the JDK `GzipInputStream` is so fundamentally broken, perhaps instead of @magicDGS's fix, we should just have our own one internally that is a copy/paste of the JDK's with a fix in place?  It wouldn't be very hard to do.

**Comment by lbergelson** [comment]
Ah, you're right about it for bam.  I was thinking of the tribble case.  

We definitely have to many ways to open things.   I would love to get rid of java.io.File completely because java.nio.file.Path should be able to handle everything that File can.  I was assuming we would do that as part of the big changes for htsjdk3 that we started talking about a while ago.  We could speed that bit up and do it first though if it would help fix this problem.  

Having our own GzipInputStream with a fix isn't a bad idea, it's a pretty common wrapper though, so it's very possible that other libraries will make use of it on top of htsjdk, which means we want our streams to be compatible with it I think.

**Comment by magicDGS** [comment]
I can't look at it soon because I have some technical problems with my computer which are slowing down ny development. I definitely agree that this is a regression that should be fixed, and I will think about it it but I usually don't work with pipes in Java. Maybe wrapping the stream in s buffered one will help.

On the other hand, I guess that htsjdk3 should be java.nio.Path implemented, and forget about File...

**Comment by tfenne** [comment]
The /dev/stdin / named-pipe regression was fixed by #1085 and #1124 (SamReaderFactory now handles non-regular files consistently for File and Path), with a follow-up edge case resolved in #1717. Reading from stdin as a Path works again. Closing.
