### ISSUE TITLE
CRAM NPE when writing using an unindexed fasta reference

### ISSUE THREAD

**Issue by lbergelson** [samtools/htsjdk#1152]
`htsjdk.samtools.cram.ref.ReferenceSource` will return null bases if the fasta reader it's wrapping is not indexed.  This then causes an NPE when writing a CRAM.

```
java.lang.NullPointerException
	at htsjdk.samtools.cram.build.Sam2CramRecordFactory.addMismatchReadFeatures(Sam2CramRecordFactory.java:292)
	at htsjdk.samtools.cram.build.Sam2CramRecordFactory.createVariations(Sam2CramRecordFactory.java:224)
	at htsjdk.samtools.cram.build.Sam2CramRecordFactory.checkedCreateVariations(Sam2CramRecordFactory.java:169)
	at htsjdk.samtools.cram.build.Sam2CramRecordFactory.createCramRecord(Sam2CramRecordFactory.java:118)
	at htsjdk.samtools.CRAMContainerStreamWriter.flushContainer(CRAMContainerStreamWriter.java:326)
	at htsjdk.samtools.CRAMContainerStreamWriter.finish(CRAMContainerStreamWriter.java:128)
	at htsjdk.samtools.CRAMFileWriter.finish(CRAMFileWriter.java:129)
	at htsjdk.samtools.SAMFileWriterImpl.close(SAMFileWriterImpl.java:229)
	at org.broadinstitute.hellbender.utils.read.ReadUtilsUnitTest.testCreatePathSAMWriter(ReadUtilsUnitTest.java:538)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
```

See [ReferenceSource.findBasesByName](https://github.com/samtools/htsjdk/blob/96ce8fb7cd28d416bff06a106d1a93ccea52ef54/src/main/java/htsjdk/samtools/cram/ref/ReferenceSource.java#L191-L193)
```
byte[] findBasesByName(final String name, final boolean tryVariants) {
        if (rsFile == null || !rsFile.isIndexed())
            return null;
```

**Comment by tfenne** [comment]
Verified on current master -- the NPE is gone, so closing.

Writing a CRAM with a deliberately unindexed reference fasta (no companion .fai) now fails with:

```
IllegalArgumentException: A reference must be supplied (reference sequence SAMSequenceRecord(name=1,...) not found).
```

rather than the `NullPointerException` in `Sam2CramRecordFactory.addMismatchReadFeatures` reported here. The reference layer no longer hands back null bases that blow up downstream.

The wording is still not ideal -- a reference *was* supplied, it just was not indexed -- but that is the separate complaint in #998, which stays open. #1732 (a closely related message on the read path) has a fix up in #1790.
