### ISSUE TITLE
Querying for multiple loci in a BAM over NIO is unacceptably slow.

### ISSUE THREAD

**Issue by yfarjoun** [samtools/htsjdk#1161]
### Verify
For example, see issue https://github.com/broadinstitute/picard/issues/1175 in Picard

### Subject of the issue
Picard CrosscheckFingerprints is one of the few programs that requires querying multiple sites of a bam file. For some reason, while doing this over NIO, the program stalls and seems to be stuck on reading the index:

```
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	- locked <0x00000001de350a30> (a java.lang.Object)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	- locked <0x00000001de350b68> (a sun.security.ssl.AppInputStream)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	- locked <0x00000005cbc20470> (a java.io.BufferedInputStream)
	at sun.net.www.MeteredStream.read(MeteredStream.java:134)
	- locked <0x00000005cbc333c0> (a sun.net.www.http.KeepAliveStream)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3375)
	at shaded.cloud_nio.com.google.api.client.http.javanet.NetHttpResponse$SizeValidatingInputStream.read(NetHttpResponse.java:169)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at shaded.cloud_nio.com.google.api.client.util.ByteStreams.copy(ByteStreams.java:51)
	at shaded.cloud_nio.com.google.api.client.util.IOUtils.copy(IOUtils.java:94)
	at shaded.cloud_nio.com.google.api.client.util.IOUtils.copy(IOUtils.java:63)
	at shaded.cloud_nio.com.google.api.client.http.HttpResponse.download(HttpResponse.java:421)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.read(HttpStorageRpc.java:522)
	at com.google.cloud.storage.BlobReadChannel$1.call(BlobReadChannel.java:127)
	at com.google.cloud.storage.BlobReadChannel$1.call(BlobReadChannel.java:124)
	at shaded.cloud_nio.com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:89)
	at com.google.cloud.RetryHelper.run(RetryHelper.java:74)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:51)
	at com.google.cloud.storage.BlobReadChannel.read(BlobReadChannel.java:124)
	at com.google.cloud.storage.contrib.nio.CloudStorageReadChannel.read(CloudStorageReadChannel.java:114)
	- locked <0x00000001db06e2b8> (a com.google.cloud.storage.contrib.nio.CloudStorageReadChannel)
	at htsjdk.samtools.seekablestream.SeekablePathStream.read(SeekablePathStream.java:86)
	at htsjdk.samtools.AbstractBAMFileIndex$IndexStreamBuffer.readFully(AbstractBAMFileIndex.java:660)
	at htsjdk.samtools.AbstractBAMFileIndex$IndexStreamBuffer.readInteger(AbstractBAMFileIndex.java:695)
	at htsjdk.samtools.AbstractBAMFileIndex.readInteger(AbstractBAMFileIndex.java:442)
	at htsjdk.samtools.AbstractBAMFileIndex.skipToSequence(AbstractBAMFileIndex.java:423)
	at htsjdk.samtools.AbstractBAMFileIndex.query(AbstractBAMFileIndex.java:277)
	at htsjdk.samtools.CachingBAMFileIndex.getQueryResults(CachingBAMFileIndex.java:163)
	at htsjdk.samtools.CachingBAMFileIndex.getSpanOverlapping(CachingBAMFileIndex.java:66)
	at htsjdk.samtools.BAMFileReader.getFileSpan(BAMFileReader.java:898)
	at htsjdk.samtools.BAMFileReader.createIndexIterator(BAMFileReader.java:915)
	at htsjdk.samtools.BAMFileReader.query(BAMFileReader.java:575)
	at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:528)
	at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.queryOverlapping(SamReader.java:400)
	at htsjdk.samtools.util.SamRecordIntervalIteratorFactory.makeSamRecordIntervalIterator(SamRecordIntervalIteratorFactory.java:76)
	at htsjdk.samtools.util.AbstractLocusIterator.iterator(AbstractLocusIterator.java:192)
	at picard.fingerprint.FingerprintChecker.fingerprintSamFile(FingerprintChecker.java:441)
	at picard.fingerprint.FingerprintChecker.lambda$fingerprintFiles$4(FingerprintChecker.java:635)
	at picard.fingerprint.FingerprintChecker$$Lambda$12/179294202.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

The problem seems to be that there is an http request for each small piece of the index.  

### Your environment
* htsjdk 2.16.0
* version of java 1.8
* Linux 2.6.32-754.el6.x86_64

### Steps to reproduce
Run CrosscheckFingerprints using picard cloud.jar against a bam in GCS or run GATK print reads with multiple (small) -L arguments and notice that the programs fail to terminate.

**Comment by tfenne** [comment]
Fixed on master for the upcoming 6.0.0 by #1810: with the default `IndexLoading.AUTO`, a BAI or CSI on a non-default filesystem is read whole in one pass instead of in many small reads; `SamReaderFactory.indexLoading(IndexLoading.EAGER)` forces that anywhere.
