### ISSUE TITLE
htsjdk.samtools.util.RuntimeIOException: Could not find BCL file for cycle 26

### ISSUE THREAD

**Issue by kemin711** [samtools/htsjdk#1171]
### Verify
Yes

### Subject of the issue
Describe your issue here.
Cannot convert bcl2sam

### Your environment
* version of htsjdk latest version
* version of java  tested on both 1.8 and 11 both gave the same
* which OS test one both ubunto, and centos

### Steps to reproduce

java -Xmx20g -jar picard.jar IlluminaBasecallsToSam BASECALLS_DIR=/remote/SeqData/180722_ST-E00243_0509_AHN2LKCCXY/Data/Intensities/BaseCalls LANE=8 BARCODES_DIR=lane8bar READ_STRUCTURE=151T6B2M6B2M151T RUN_BARCODE=HISEQNOVO NUM_PROCESSORS=8 LIBRARY_PARAMS=picard_sample_sheet_library8.tab

### Expected behaviour
I had 4 lanes from 5-8. It worked fine for land 5-7, at lane 8 I got the error message.
The bcl files are find. We can get fastq files with bcl2fastq (ILLUMINA) program for this lane

### Actual behaviour
Crashed at lane 8 cycle 26.  Files are there for cycle 26.  Not sure how to verify

INFO    2018-08-01 08:26:34     BasecallsConverter      Write   177,000,000 records.  Elapsed time: 00:26:56s.  Time for last 1,000,000:    4s.  Last read position: */*
INFO    2018-08-01 08:26:35     BasecallsConverter      Read   215,000,000 records.  Elapsed time: 00:26:56s.  Time for last 1,000,000:   14s.  Last read position: */*
INFO    2018-08-01 08:26:39     BasecallsConverter      Write   178,000,000 records.  Elapsed time: 00:27:00s.  Time for last 1,000,000:    4s.  Last read position: */*
INFO    2018-08-01 08:26:42     BasecallsConverter      Write   179,000,000 records.  Elapsed time: 00:27:04s.  Time for last 1,000,000:    3s.  Last read position: */*
INFO    2018-08-01 08:26:47     BasecallsConverter      Write   180,000,000 records.  Elapsed time: 00:27:08s.  Time for last 1,000,000:    4s.  Last read position: */*
INFO    2018-08-01 08:26:50     BasecallsConverter      Read   216,000,000 records.  Elapsed time: 00:27:11s.  Time for last 1,000,000:   15s.  Last read position: */*
INFO    2018-08-01 08:26:51     BasecallsConverter      Write   181,000,000 records.  Elapsed time: 00:27:12s.  Time for last 1,000,000:    3s.  Last read position: */*
INFO    2018-08-01 08:26:57     BasecallsConverter      Write   182,000,000 records.  Elapsed time: 00:27:18s.  Time for last 1,000,000:    5s.  Last read position: */*
INFO    2018-08-01 08:27:01     BasecallsConverter      Write   183,000,000 records.  Elapsed time: 00:27:23s.  Time for last 1,000,000:    4s.  Last read position: */*
INFO    2018-08-01 08:27:04     BasecallsConverter      Read   217,000,000 records.  Elapsed time: 00:27:25s.  Time for last 1,000,000:   14s.  Last read position: */*
INFO    2018-08-01 08:27:07     BasecallsConverter      Write   184,000,000 records.  Elapsed time: 00:27:28s.  Time for last 1,000,000:    5s.  Last read position: */*
INFO    2018-08-01 08:27:11     BasecallsConverter      Write   185,000,000 records.  Elapsed time: 00:27:32s.  Time for last 1,000,000:    3s.  Last read position: */*
INFO    2018-08-01 08:27:15     BasecallsConverter      Read   218,000,000 records.  Elapsed time: 00:27:36s.  Time for last 1,000,000:   10s.  Last read position: */*
INFO    2018-08-01 08:27:15     BasecallsConverter      Write   186,000,000 records.  Elapsed time: 00:27:36s.  Time for last 1,000,000:    3s.  Last read position: */*
INFO    2018-08-01 08:27:19     BasecallsConverter      Write   187,000,000 records.  Elapsed time: 00:27:40s.  Time for last 1,000,000:    4s.  Last read position: */*
INFO    2018-08-01 08:27:23     BasecallsConverter      Read   219,000,000 records.  Elapsed time: 00:27:45s.  Time for last 1,000,000:    8s.  Last read position: */*
INFO    2018-08-01 08:27:24     BasecallsConverter      Write   188,000,000 records.  Elapsed time: 00:27:45s.  Time for last 1,000,000:    4s.  Last read position: */*
INFO    2018-08-01 08:27:30     BasecallsConverter      Write   189,000,000 records.  Elapsed time: 00:27:51s.  Time for last 1,000,000:    5s.  Last read position: */*
INFO    2018-08-01 08:27:32     BasecallsConverter      Read   220,000,000 records.  Elapsed time: 00:27:53s.  Time for last 1,000,000:    8s.  Last read position: */*
INFO    2018-08-01 08:27:34     BasecallsConverter      Write   190,000,000 records.  Elapsed time: 00:27:55s.  Time for last 1,000,000:    4s.  Last read position: */*
Exception in thread "pool-2-thread-3" ERROR     2018-08-01 08:27:34     IlluminaBasecallsConverter      Failure encountered in worker thread; attempting to shut down remaining worker thread
s and terminate ...
java.lang.InterruptedException
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at picard.illumina.IlluminaBasecallsConverter$TileReadAggregator.awaitWorkComplete(IlluminaBasecallsConverter.java:609)
        at picard.illumina.IlluminaBasecallsConverter.doTileProcessing(IlluminaBasecallsConverter.java:234)
        at picard.illumina.IlluminaBasecallsToSam.doWork(IlluminaBasecallsToSam.java:273)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:282)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)
htsjdk.samtools.util.RuntimeIOException: Could not find BCL file for cycle 26
        at picard.illumina.parser.readers.BclReader.<init>(BclReader.java:89)
        at picard.illumina.parser.BclParser$BclDataCycleFileParser.<init>(BclParser.java:269)
        at picard.illumina.parser.BclParser.makeCycleFileParser(BclParser.java:75)
        at picard.illumina.parser.PerTileCycleParser.makeCycleFileParser(PerTileCycleParser.java:97)
        at picard.illumina.parser.PerTileCycleParser.seekToTile(PerTileCycleParser.java:133)
        at picard.illumina.parser.BclParser.initialize(BclParser.java:80)
        at picard.illumina.parser.BclParser.<init>(BclParser.java:63)
        at picard.illumina.parser.IlluminaDataProviderFactory.makeParser(IlluminaDataProviderFactory.java:408)
        at picard.illumina.parser.IlluminaDataProviderFactory.makeDataProvider(IlluminaDataProviderFactory.java:292)
        at picard.illumina.IlluminaBasecallsConverter$TileReader.process(IlluminaBasecallsConverter.java:463)
        at picard.illumina.IlluminaBasecallsConverter$TileReadAggregator$1.run(IlluminaBasecallsConverter.java:560)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Exception in thread "pool-2-thread-1" htsjdk.samtools.util.RuntimeIOException: Read error; BinaryCodec in readmode; streamed file (filename not available)
        at htsjdk.samtools.util.BinaryCodec.readBytesOrFewer(BinaryCodec.java:420)
        at htsjdk.samtools.util.BinaryCodec.readBytes(BinaryCodec.java:394)
        at htsjdk.samtools.util.BinaryCodec.readBytes(BinaryCodec.java:380)
        at htsjdk.samtools.BAMRecordCodec.decode(BAMRecordCodec.java:209)
        at picard.illumina.IlluminaBasecallsToSam$Codec.decode(IlluminaBasecallsToSam.java:628)
        at picard.illumina.IlluminaBasecallsToSam$Codec.decode(IlluminaBasecallsToSam.java:587)
        at htsjdk.samtools.util.SortingCollection$FileRecordIterator.advance(SortingCollection.java:544)   
        at htsjdk.samtools.util.SortingCollection$FileRecordIterator.next(SortingCollection.java:534)
        at htsjdk.samtools.util.PeekIterator.peek(PeekIterator.java:69)
        at htsjdk.samtools.util.SortingCollection$PeekFileRecordIteratorComparator.compare(SortingCollection.java:570)
        at htsjdk.samtools.util.SortingCollection$PeekFileRecordIteratorComparator.compare(SortingCollection.java:565)
        at java.util.TreeMap.put(TreeMap.java:552)
        at java.util.TreeSet.add(TreeSet.java:255)
        at htsjdk.samtools.util.SortingCollection$MergingIterator.next(SortingCollection.java:478)
        at htsjdk.samtools.util.PeekIterator.peek(PeekIterator.java:69)
        at picard.illumina.IlluminaBasecallsConverter$TileReadAggregator$2.run(IlluminaBasecallsConverter.java:716)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.channels.ClosedByInterruptException
        at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)   
        at sun.nio.ch.FileChannelImpl.size(FileChannelImpl.java:315)
        at sun.nio.ch.ChannelInputStream.available(ChannelInputStream.java:116)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:353)
        at org.xerial.snappy.SnappyInputStream.hasNextChunk(SnappyInputStream.java:426)
        at org.xerial.snappy.SnappyInputStream.read(SnappyInputStream.java:167)
        at htsjdk.samtools.util.BinaryCodec.readBytesOrFewer(BinaryCodec.java:418)
        ... 18 more
[thread 140036196566784 also had an error]#

# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f5c377cc440, pid=23472, tid=0x00007f5c371bb700
#
# JRE version: OpenJDK Runtime Environment (8.0_102-b14) (build 1.8.0_102-b14)

**Comment by yfarjoun** [comment]
@jacarey does this make sense to you?

@kemin711 what about running IlluminaBasecallsToFastq? does it fail in the same place?

**Comment by jacarey** [comment]
This is a segmentation fault in the jvm. Could we get a core dump to analyze?

**Comment by kemin711** [comment]
I wrote my own C++ program to solve this problem.
Kemin Zhou 858 771-3269 

    On Wednesday, August 1, 2018, 11:37:56 AM PDT, Yossi Farjoun <notifications@github.com> wrote:  
 
 
@jacarey does this make sense to you?

@kemin711 what about running IlluminaBasecallsToFastq? does it fail in the same place?

**Comment by tfenne** [comment]
Closing — this comes from Picard's `IlluminaBasecallsToSam`; htsjdk itself contains no BCL or Illumina basecall parsing code. If it still reproduces on a current Picard, the right place for it is https://github.com/broadinstitute/picard/issues.
