### ISSUE TITLE
*htslib CRAM test file md#1 fails round-trips in CramComplianceTest

### ISSUE THREAD

**Issue by jmthibault79** [samtools/htsjdk#1187]
### Subject of the issue
Adding the `md#1` files and test case to a private branch causes these failures:
```
ERROR	2018-10-05 11:36:57	Sam2CramRecordFactory	Reference bases array length=40
ERROR	2018-10-05 11:36:57	Sam2CramRecordFactory	Offensive CRAM record: [xIP; flags=0; alignmentOffset=0; mateOffset=-1; mappingQuality=255]
ERROR	2018-10-05 11:36:57	Sam2CramRecordFactory	Offensive SAM record: xIP	0	a	1	255	1I10M1I10M2I10M2P3I2P10M1I	*	0	0	NAAAAAAAAAAGCCCCCCCCCCAAGGGGGGGGGGCCCTTTTTTTTTTN	*	MD:Z:18Y0N0N0R18	NM:i:12

java.lang.ArrayIndexOutOfBoundsException: 20

	at htsjdk.samtools.cram.build.Sam2CramRecordFactory.addMismatchReadFeatures(Sam2CramRecordFactory.java:302)
	at htsjdk.samtools.cram.build.Sam2CramRecordFactory.createVariations(Sam2CramRecordFactory.java:224)
	at htsjdk.samtools.cram.build.Sam2CramRecordFactory.checkedCreateVariations(Sam2CramRecordFactory.java:169)
	at htsjdk.samtools.cram.build.Sam2CramRecordFactory.createCramRecord(Sam2CramRecordFactory.java:118)
	at htsjdk.samtools.CRAMContainerStreamWriter.flushContainer(CRAMContainerStreamWriter.java:326)
	at htsjdk.samtools.CRAMContainerStreamWriter.finish(CRAMContainerStreamWriter.java:128)
	at htsjdk.samtools.CRAMFileWriter.finish(CRAMFileWriter.java:129)
	at htsjdk.samtools.SAMFileWriterImpl.close(SAMFileWriterImpl.java:215)
	at htsjdk.samtools.CRAMComplianceTest.doComplianceTest(CRAMComplianceTest.java:162)
```

### Your environment
* version of htsjdk: private branch off master (49c70e5b394d303b47bd894d430f78f08aefc268)
* version of java: Java 1.8.0_171 / IntelliJ CE 2018.1.6
* which OS: Mac OS X High Sierra 10.13.6

**Comment by cmnbroad** [comment]
Fixed in refactoring branch.

**Comment by cmnbroad** [comment]
Fixed via https://github.com/samtools/htsjdk/pull/1440.
