### ISSUE TITLE
Problem with tribble "has index" logic

### ISSUE THREAD

**Issue by jrobinso** [samtools/htsjdk#1405]
Hi, I got an IGV report that remote gff3 files could not be loaded, an error is thrown if a tribble index does not exist.    The problem is here, line 124 of TribbleIndexedFeatureReader

```
   public boolean hasIndex() {
        if (this.index == null && this.needCheckForIndex) {
            try {
                this.loadIndex();
            } catch (IOException var2) {
                throw new TribbleException("Error loading index file: " + var2.getMessage(), var2);
            }
        }

        return this.index != null;
    }
```

If the remote index does not exist an error is thrown.  IGV calls this function to see if the reader is indexed or not,  the expectation is that hasIndex() would tell me that, not that it would have side effects making the file unreadable.    However the real flaw might be in the needCheckForIndex flag.  I am instantiating the reader as follows,  the last argument is requiresIndex which is false.  Its already known by IGV that this file does not have an index.

```
AbstractFeatureReader.getFeatureReader(path, idxPath, codec, false)
```

Even so,  needCheckForIndex is set to true,  thus the call to hasIndex() throws an error making the file unreadable.   I think this behavior has to be fairly new.    My suggestion is to trace the logic for needCheckForIndex, in particular when it is set to true when requiresIndex is false.

**Comment by jrobinso** [comment]
Alternative solution would be to supply a method to determine if a reader is queryable, or has an index,  without any side effects.    Maybe

```
public boolean isIndexed() {
    return this.index != null;
}
```

**Comment by lbergelson** [comment]
This is weird behavior...  A method called `hasIndex()` really shouldn't throw.  We are pretty inconsistent though about what we do in cases where we can't determine a clear answer because there was an unexpected error.  Some times you'd want that to be reported and sometimes you want to silently continue so I see how we got in this position.  

Do you have a full stack trace or the exact error message?  It looks like if the file doesn't exist is should be reported as missing by `ParsingUtils.resourceExists` and you wouldn't get an exception.

**Comment by jrobinso** [comment]
Hi @lbergelson thanks for the quick response.   Stack trace is below.   I do not get this error when loading a File, it behaves as expected, only when loading by URL.   This is a new problem, how new I'm not sure but fairly recent.

```
htsjdk.tribble.TribbleException$UnableToCreateCorrectIndexType: Unknown index type.  magic number: 0x37726863; type 1447118857
	at htsjdk.tribble.index.IndexFactory$IndexType.getIndexType(IndexFactory.java:152) ~[htsjdk-2.19.0-48-g45cfc08-SNAPSHOT.jar:2.19.0-48-g45cfc08-SNAPSHOT]
	at htsjdk.tribble.index.IndexFactory.loadIndex(IndexFactory.java:192) ~[htsjdk-2.19.0-48-g45cfc08-SNAPSHOT.jar:2.19.0-48-g45cfc08-SNAPSHOT]
	at htsjdk.tribble.index.IndexFactory.loadIndex(IndexFactory.java:177) ~[htsjdk-2.19.0-48-g45cfc08-SNAPSHOT.jar:2.19.0-48-g45cfc08-SNAPSHOT]
	at htsjdk.tribble.TribbleIndexedFeatureReader.loadIndex(TribbleIndexedFeatureReader.java:163) ~[htsjdk-2.19.0-48-g45cfc08-SNAPSHOT.jar:2.19.0-48-g45cfc08-SNAPSHOT]
	at htsjdk.tribble.TribbleIndexedFeatureReader.hasIndex(TribbleIndexedFeatureReader.java:228) ~[htsjdk-2.19.0-48-g45cfc08-SNAPSHOT.jar:2.19.0-48-g45cfc08-SNAPSHOT]
	at org.broad.igv.track.TribbleFeatureSource.getFeatureSource(TribbleFeatureSource.java:116) ~[classes/:?]
```

**Comment by jrobinso** [comment]
And the test url for this is  ```https://www.dropbox.com/s/kdqu0bbp1c1tfcl/egfr.gff3?dl=0```

**Comment by jrobinso** [comment]
@lbergelson I can solve this problem in IGV,  I really don't need to call hasIndex() in this case since I already know if there is an index, or not, so no urgency for IGV's sake,

**Comment by lbergelson** [comment]
I think this is related to the error you reported about identifying the index file in dropbox (#1398 ).  It looks like the value it's reading as the magic number is 0x37726863 which is the little-endian interpretation of the first 4 bytes of the ascii 'chr7' which happens to the be the first bytes of the egfr.gff3 file.

Is this with your patch to avoid auto-finding the dropbox indexes?

**Comment by jrobinso** [comment]
Ahh, duh, good point I should have noticed that.   I did not submit a patch for this, rather I test for it in IGV and don't try to test for existence for dropbox and google drive URLs.   The problem was in this instance I called  hasIndex() when it wasn't needed.    

This is my fault, but in retrospect 10 years later trying to test for existence of remote files so we can infer an index was a bad idea.    If doing this over I would remove resourceExists for everything except local files and require an explicit index for remote ones.     

As it is you can leave this open if you have any interest in supporting dropbox URLs,  or close it if not,  I am dealing with it in IGV and avoiding the call to hasIndex().   OTOH it's not nice behavior to throw an exception from such an innocuous appearing method.  Perhaps the error should be logged and return "false" in this case,  the interpretation being there is no readable or proper index.

**Comment by tfenne** [comment]
Closing, as `hasIndex()` behaves consistently and the failure reported here came from the server. Checked on current master (unreleased 6.0.0):

- **A missing index is not an error.** `hasIndex()` returns `false` when neither `x.idx` nor `x.idx.gz` is there, locally or remotely; a URL answering 404, 403 or 500 all give `false`.
- **It throws only when something is at the index location but cannot be read as an index** (wrong format, or corrupt), and it does so for a local file exactly as for a URL: a local `x.bed.idx` that is really a copy of `x.bed` throws the same `UnableToCreateCorrectIndexType`. Treating a corrupt index as absent would hide a real problem.
- **Here the index URL answered 200 with the GFF3 itself**: a Dropbox shared link serves the file its key names, whatever file name follows it, so htsjdk found data where the index should be (magic number `0x37726863` is `chr7`).
- **Nothing reads the index early.** Opening a reader with `requireIndex=false` (directly or via `AbstractFeatureReader.getFeatureReader(..., false)`) and iterating never touch it; it is read only by `hasIndex()`, `isQueryable()`, `getSequenceNames()`, `query()`, or when an index is required. In the stack trace above it was IGV's `TribbleFeatureSource` calling `hasIndex()`.

A caller that knows a host serves something for any name can skip the check for such URLs, as IGV now does for Dropbox and Google Drive, or catch `TribbleException`. We could add a non-throwing "is a readable index there right now?" method, but it isn't clear it would be useful; please open a new issue if you need one.
