### ISSUE TITLE
CRAM rewriting fails on assert

### ISSUE THREAD

**Issue by kshakir** [samtools/htsjdk#148]
I'm not going to say I think it's CRAM and the NM tag<sup>[1]</sup>, but I think it's CRAM and the NM tag<sup>[2],[3]</sup>.

This command line works, using the test crams in the current cramtools master branch<sup>[4]</sup>:

```bash
$ java \
  -jar ~/src/picard/dist/picard.jar SamFormatConverter \
  R= ~/src/cramtools/src/test/resources/data/set1/small.fa \
  I= ~/src/cramtools/src/test/resources/data/set1/small.cram \
  O= test.cram
[Sun Dec 21 10:05:07 EST 2014] picard.sam.SamFormatConverter INPUT=test.bam OUTPUT=test.cram REFERENCE_SEQUENCE=/Users/kshakir/src/cramtools/src/test/resources/data/set1/small.fa    VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false
[Sun Dec 21 10:05:07 EST 2014] Executing as kshakir@rm51f-e7b.local on Mac OS X 10.9.5 x86_64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_25-b17; Picard version: 1.126(5b984f92664175debe3826040fdae1496d1d8fa7_1418347776) JdkDeflater
[Sun Dec 21 10:05:08 EST 2014] picard.sam.SamFormatConverter done. Elapsed time: 0.02 minutes.
Runtime.totalMemory()=163053568
$
```

The same command with the addition of `-ea` crashes on an assert<sup>[5]</sup>:

```bash
$ java -ea \
  -jar ~/src/picard/dist/picard.jar SamFormatConverter \
  R= ~/src/cramtools/src/test/resources/data/set1/small.fa \
  I= ~/src/cramtools/src/test/resources/data/set1/small.cram \
  O= test.cram
[Sun Dec 21 10:05:19 EST 2014] picard.sam.SamFormatConverter INPUT=test.bam OUTPUT=test.cram REFERENCE_SEQUENCE=/Users/kshakir/src/cramtools/src/test/resources/data/set1/small.fa    VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false
[Sun Dec 21 10:05:19 EST 2014] Executing as kshakir@rm51f-e7b.local on Mac OS X 10.9.5 x86_64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_25-b17; Picard version: 1.126(5b984f92664175debe3826040fdae1496d1d8fa7_1418347776) JdkDeflater
[Sun Dec 21 10:05:19 EST 2014] picard.sam.SamFormatConverter done. Elapsed time: 0.01 minutes.
Runtime.totalMemory()=128974848
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.AssertionError
	at htsjdk.samtools.CRAMFileWriter.flushContainer(CRAMFileWriter.java:275)
	at htsjdk.samtools.CRAMFileWriter.finish(CRAMFileWriter.java:337)
	at htsjdk.samtools.SAMFileWriterImpl.close(SAMFileWriterImpl.java:205)
	at picard.sam.SamFormatConverter.doWork(SamFormatConverter.java:88)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:187)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:89)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:99)
$
```

[1]: http://www.ebi.ac.uk/ena/software/archive-cram-specification-1-0#computed_tags
[2]: https://github.com/samtools/htsjdk/blob/18192d82063a69c77072436503f14b527e2e1be7/src/java/htsjdk/samtools/cram/build/Sam2CramRecordFactory.java#L76
[3]: https://github.com/samtools/htsjdk/blob/18192d82063a69c77072436503f14b527e2e1be7/src/java/htsjdk/samtools/CRAMIterator.java#L50
[4]: https://github.com/enasequence/cramtools/tree/master/src/test/resources/data/set1
[5]: https://github.com/samtools/htsjdk/blob/18192d82063a69c77072436503f14b527e2e1be7/src/java/htsjdk/samtools/CRAMFileWriter.java#L275

**Comment by nh13** [comment]
@vadimzalunin any movement on this?

**Comment by nh13** [comment]
@vadimzalunin : please write a unit test that re-creates the failure, then submit a fix taht  passes after the fix is applied.

**Comment by vadimzalunin** [comment]
fixed in https://github.com/samtools/htsjdk/pull/224

**Comment by cmnbroad** [comment]
@vadimzalunin Can this be closed ?
