### ISSUE TITLE
Add a better error message when the reference is too long for indexing

### ISSUE THREAD

**Issue by lbergelson** [samtools/htsjdk#1651]
There have been two seperate issues this week with people running into a confusing indexing error when using a long reference.  We should give a better error.  We should ideally also identify this problem upfront instead of crashing late.

See https://github.com/broadinstitute/gatk/issues/8192 and [this gatk forum post](https://gatk.broadinstitute.org/hc/en-us/community/posts/12862204385051-Is-it-feasible-to-use-the-extracted-vcf-gz-file-for-CombineGVCFs-and-GenotypeGVCFs-?page=1#community_comment_12873118427291)

```
java.lang.ArrayIndexOutOfBoundsException: Index 32770 out of bounds for length 32770
        at htsjdk.samtools.BinningIndexBuilder.processFeature(BinningIndexBuilder.java:142)
        at htsjdk.tribble.index.tabix.TabixIndexCreator.finalizeFeature(TabixIndexCreator.java:106)
        at htsjdk.tribble.index.tabix.TabixIndexCreator.finalizeIndex(TabixIndexCreator.java:129)
        at htsjdk.variant.variantcontext.writer.IndexingVariantContextWriter.close(IndexingVariantContextWriter.java:177)
        at htsjdk.variant.variantcontext.writer.VCFWriter.close(VCFWriter.java:233)
        at org.broadinstitute.hellbender.utils.variant.writers.GVCFWriter.close(GVCFWriter.java:71)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCaller.closeTool(HaplotypeCaller.java:277)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1101)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
        at org.broadinstitute.hellbender.Main.main(Main.java:289)
```

**Comment by hjt1129** [comment]
hi, we have also meet this problem. So one question is, if we split the large chromosome in reference genome, the final location information of SNP on splitted chromosome will be different with the gff annotation file of previous vision reference genome?

**Comment by lbergelson** [comment]
@hjt1129 Yes, it's not a perfect solution.  It definitely complicates annotation and comparison.  You would need to either reverse the splitting before comparing with the gff or perform the same split on the gff in order to compare.  

We'd like to support CSI for vcf but we haven't had the time to do so.

**Comment by jd3234** [comment]
I have also run into this problem trying to use VariantQC for a VCF based on a wheat genome. These very large plant genomes require csi indices. Any chance to support this from your side? Plant world is catching up with sequencing ;)

**Comment by WimSpee** [comment]
@lbergelson  The `--create-output-variant-index false` workaround unfortunately does not work. 
Still same `Index 32770 out of bounds for length 32770` error. 

This seems to be because HaplotypeCaller requires a BAI index file next to the input CRAM file. 
When no  CRAI index file is next to the input CRAM file this error is given. 
```
org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCaller done. Elapsed time: 0.01 minutes.
Runtime.totalMemory()=285212672
***********************************************************************

A USER ERROR has occurred: Traversal by intervals was requested but some input files are not indexed.
Please index all input files:
```
BAI index is not possible because of the chromosome sizes. 

I am not sure if an index is really needed for the input CRAM file for HaplotypeCaller to do its work. 
If it would be possible for HaplotypeCaller to do it work without an input CRAM index, that would be a preferable workaround for us, compared to splitting the chromosomes.  Next to of course CRAI support :) 

Thank you.

**Comment by lbergelson** [comment]
@WimSpee I'm sorry.  I gave you bad advice.  I thought HaplotypeCaller would run without an index if you didn't give it any `-L` argument, most GATK tools do.  It looks like it does some complicated internal sharding though, which ends up using an index.  I don't see any easy work around here.  It would be great to add CRAI/CSI support but I don't have any timeline for it.

**Comment by WimSpee** [comment]
@lbergelson  Just to let you know, and other people finding this issue, the workaround you suggested now works in GATK 4.6.1.0.  

Adding `--create-output-variant-index false` now enables  GATK 4.6.1.0. HaplotypeCaller to create a gVCF file for a BAM file of a species having 2Gb chromosomes. 

Maybe this can also be added to the HaplotypeCaller documentation web page. Since the error still isn't very informative. 

GATK 4.6.1.0. GenomicsDbImport (and thus GenotypeGVCFs) can't accept those gVCF files, because they require a TBI index, which can't be created, for those files. 

A CSI index can be created for the gVCF files that GATK 4.6.1.0. HaplotypeCaller created (via e.g. bcftools index)

Multi-sample variant calling is then possible e.g. via an HTSLIB based tool like GLnexus. 

Thank you , and the (other) GATK developers for making this workaround work for people working on species with 500Mb+ chromosomes.

**Comment by tfenne** [comment]
Fixed on master for the upcoming 6.0.0. Indexing a position beyond 2^29 with a TBI or BAI now fails with a message that says the position is beyond what that index's fixed binning scheme can address and that a CSI is needed, instead of `ArrayIndexOutOfBoundsException: Index 32770`.

And CSI is now there to use: `VariantContextWriterBuilder.setTabixIndexType(TabixIndexType.CSI)` for VCF and other tabix-indexed files (#1807), `SAMFileWriterFactory.setBamIndexType(BamIndexType.CSI)` for BAM, or `BamIndexType.AUTO` to get a CSI only when a sequence is too long for a BAI (#1809). The CRAM case raised in the comments is covered too: CRAM region queries are answered from the CRAI directly, which has no such limit (#1798).
