### ISSUE TITLE
IndexFactory.createTabixIndex() is not able to handle block-compressed files

### ISSUE THREAD

**Issue by droazen** [samtools/htsjdk#184]
Currently, if you pass a block-compressed file into `IndexFactory.createTabixIndex()`, the file never gets decompressed internally, causing the underlying codec to blow up with errors like the following:

        Exception in thread "main" htsjdk.tribble.TribbleException$InvalidHeader: Your input file has a malformed header: We never saw the required CHROM header line (starting with one #) for the input VCF file
	at htsjdk.variant.vcf.VCFCodec.readActualHeader(VCFCodec.java:115)
	at htsjdk.tribble.AsciiFeatureCodec.readHeader(AsciiFeatureCodec.java:88)
	at htsjdk.tribble.AsciiFeatureCodec.readHeader(AsciiFeatureCodec.java:41)
	at htsjdk.tribble.index.IndexFactory$FeatureIterator.readHeader(IndexFactory.java:413)
	at htsjdk.tribble.index.IndexFactory$FeatureIterator.<init>(IndexFactory.java:401)
	at htsjdk.tribble.index.IndexFactory.createTabixIndex(IndexFactory.java:327)

I see two possible solutions, and wanted to solicit feedback on which would be preferable:

1. Create an overload of `createTabixIndex()` that accepts a stream rather than a File (this places the burden of setting up the stream correctly on the client)

2. Have the existing `FeatureIterator.initStream()` check for block-compressed input via `AbstractFeatureReader.hasBlockCompressedExtension()`, and wrap the stream returned within a `BlockCompressedInputStream` as needed.

Thoughts?

**Comment by jmthibault79** [comment]
I like option 2, so calling it just works.  What are the downsides to this solution?

I noticed that there are two `FeatureIterator` classes with similar signatures, so we may want to improve this confusing situation as well.

**Comment by jmthibault79** [comment]
See also #185 !

**Comment by mattsooknah** [comment]
I also prefer option 2 - it should be the factory's job to handle this sort of thing.

**Comment by vdauwera** [comment]
Folks, it looks like we have two solutions for the same problem here. Can we get a show of hands for what's preferred between #185 and #217?

**Comment by vdauwera** [comment]
Umm, looks like I'm late to the party, #217 has been merged. Never mind.
