### ISSUE TITLE
"NoSuchElementException: None.get" on sbt build

### ISSUE THREAD

**Issue by dmyersturnbull** [samtools/htsjdk#265]
When I run `sbt compile` on release 1.133 using sbt 0.13.8, Java 1.8.0_25 and Scala 2.11.6, I get:

```
java.util.NoSuchElementException: None.get
    at scala.None$.get(Option.scala:313)
    at scala.None$.get(Option.scala:311)
    at $a2d680e91f701eb7878a$$anonfun$$sbtdef$1.apply(/Users/douglas/Desktop/htsjdk-1.133/build.sbt:55)
    at $a2d680e91f701eb7878a$$anonfun$$sbtdef$1.apply(/Users/douglas/Desktop/htsjdk-1.133/build.sbt:55)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
    at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
    at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
    at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
    at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[error] java.util.NoSuchElementException: None.get
```

Running `ant htsjdk-jar` completes successfully.

**Comment by lbergelson** [comment]
Hi @dmyersturnbull.  Thanks for the report.  

`ant` is the currently supported build tool for htsjdk.    The `sbt` build is used for publishing the build to maven central and isn't tested for other purposes.  It's confusing to have both build files in there, and it's possible that `sbt` will be fully supported in the future, but for now just use `ant`.

**Comment by dmyersturnbull** [comment]
Forgot to close. It looks like you've moved to Gradle, anyways.

**Comment by lbergelson** [comment]
@dmyersturnbull Thanks for cleaning up.
