### ISSUE TITLE
"main" java.lang.UnsatisfiedLinkError: gov.nih.nlm.ncbi.ngs.Manager.SetAppVersionString(Ljava/lang/String;)V

### ISSUE THREAD

**Issue by lindenb** [samtools/htsjdk#409]
not sure if it's a bug or if this belongs to picard.
I was playing with 

```
htsjdk-2.0.1/testdata/htsjdk/samtools/unsorted.sam
```

and picard

```
java -jar picard-tools-2.0.1/picard.jar SortSam I=htsjdk-2.0.1/testdata/htsjdk/samtools/unsorted.sam  O=out.bam SO=unsorted
```

but I get the following (JNI ?) exception:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: gov.nih.nlm.ncbi.ngs.Manager.SetAppVersionString(Ljava/lang/String;)V
	at gov.nih.nlm.ncbi.ngs.Manager.SetAppVersionString(Native Method)
	at gov.nih.nlm.ncbi.ngs.Manager.setAppVersionString(Manager.java:49)
	at gov.nih.nlm.ncbi.ngs.NGS.setAppVersionString(NGS.java:60)
	at htsjdk.samtools.sra.SRAAccession.isSupported(SRAAccession.java:67)
	at htsjdk.samtools.sra.SRAAccession.isValid(SRAAccession.java:78)
	at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:275)
	at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:134)
	at picard.sam.SortSam.doWork(SortSam.java:73)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:209)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:95)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:105)
```

**Comment by yfarjoun** [comment]
Hi Pierre,

Can I ask you to try it with the PR #407 and see if it changes anything?

Thanks!


On Tue, Dec 15, 2015 at 7:51 AM, Pierre Lindenbaum <notifications@github.com

**Comment by lindenb** [comment]
Thanks : Using htsjdk *.jars from https://github.com/samtools/htsjdk/pull/407 with a private program that reads SAM fixed the problem

**Comment by yfarjoun** [comment]
Great. thanks.

On Tue, Dec 15, 2015 at 8:15 AM, Pierre Lindenbaum <notifications@github.com

**Comment by magicDGS** [comment]
Could this be closed?
