### ISSUE TITLE
NPE when validating a CRAM file with a .fasta reference with no .dict file

### ISSUE THREAD

**Issue by cmnbroad** [samtools/htsjdk#513]
If you pass in a .fasta file for which there is no corresponding .dict file to SamFileValidator you'll get an NPE during NM tag validation. Even though the bug isn't specific to CRAM files, I'm tagging it with the CRAM tag since its way more likely to happen when you're required to pass a reference, as is the case for CRAM files.

java.lang.NullPointerException
    at htsjdk.samtools.reference.ReferenceSequenceFileWalker.get(ReferenceSequenceFileWalker.java:87)
    at htsjdk.samtools.SamFileValidator.validateNmTag(SamFileValidator.java:462)
    at htsjdk.samtools.SamFileValidator.validateSamRecordsAndQualityFormat(SamFileValidator.java:288)
    at htsjdk.samtools.SamFileValidator.validateSamFile(SamFileValidator.java:200)
    at htsjdk.samtools.SamFileValidator.validateSamFileVerbose(SamFileValidator.java:160)
    at org.broadinstitute.hellbender.tools.picard.sam.ValidateSamFile.doWork(ValidateSamFile.java:131)
    at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:98)
    at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:146)
    at org.broadinstitute.hellbender.cmdline.PicardCommandLineProgram.instanceMain(PicardCommandLineProgram.java:61)
    at org.broadinstitute.hellbender.Main.instanceMain(Main.java:66)
    at org.broadinstitute.hellbender.Main.instanceMain(Main.java:73)
    at org.broadinstitute.hellbender.CommandLineProgramTest.runCommandLine(CommandLineProgramTest.java:72)
    at org.broadinstitute.hellbender.tools.picard.sam.ValidateSamFileIntegrationTest.testJunkFile(ValidateSamFileIntegrationTest.java:76)

**Comment by vadimzalunin** [comment]
fixed https://github.com/samtools/htsjdk/pull/735
