### ISSUE TITLE
VCF4Parser.parseLine throws exception on optional Source and Version tags in INFO header

### ISSUE THREAD

**Issue by heuermh** [samtools/htsjdk#517]
Given VCFv4.2 header with Source and Version tags in `##INFO` header line

```
##fileformat=VCFv4.2
...
##INFO=<ID=ENST,Number=.,Type=String,Description="Ensembl transcript identifier",Source="savant",Version="1.1.0">
```

we're getting an exception thrown from htsjdk via HadoopBam

```
Caused by: htsjdk.tribble.TribbleException$InvalidHeader: Your input file has a malformed header: unexpected tag count 6 in line <ID=ENST,Number=.,Type=String,Description="Ensembl transcript identifier",Source="savant",Version="1.1.0">
    at htsjdk.variant.vcf.VCF4Parser.parseLine(VCFHeaderLineTranslator.java:109)
    at htsjdk.variant.vcf.VCFHeaderLineTranslator.parseLine(VCFHeaderLineTranslator.java:51)
    at htsjdk.variant.vcf.VCFCompoundHeaderLine.<init>(VCFCompoundHeaderLine.java:164)
    at htsjdk.variant.vcf.VCFInfoHeaderLine.<init>(VCFInfoHeaderLine.java:48)
    at htsjdk.variant.vcf.AbstractVCFCodec.parseHeaderFromLines(AbstractVCFCodec.java:199)
    at htsjdk.variant.vcf.VCFCodec.readActualHeader(VCFCodec.java:111)
    at htsjdk.tribble.AsciiFeatureCodec.readHeader(AsciiFeatureCodec.java:88)
    at org.seqdoop.hadoop_bam.VCFRecordReader.initialize(VCFRecordReader.java:87)
    at org.seqdoop.hadoop_bam.VCFInputFormat.createRecordReader(VCFInputFormat.java:189)
    at org.apache.spark.rdd.NewHadoopRDD$$anon$1.<init>(NewHadoopRDD.scala:149)
    at org.apache.spark.rdd.NewHadoopRDD.compute(NewHadoopRDD.scala:122)
    at org.apache.spark.rdd.NewHadoopRDD.compute(NewHadoopRDD.scala:63)
```

The same stack trace can be replicated by Picard

``` bash
$ Picard SortVcf INPUT=info.v4.2.vcf OUTPUT=info.v4.2.sorted.vcf
[Tue Mar 08 12:37:32 CST 2016] picard.vcf.SortVcf INPUT=[info.v4.2.vcf] OUTPUT=info.v4.2.sorted.vcf    VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=true CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json
...
Exception in thread "main" htsjdk.tribble.TribbleException$MalformedFeatureFile: Unable to parse header with error: Your input file has a malformed header: unexpected tag count 6 in line <ID=ENST,Number=.,Type=String,Description="Ensembl transcript identifier",Source="savant",Version="1.1.0">, for input source: info.v4.2.vcf
    at htsjdk.tribble.TribbleIndexedFeatureReader.readHeader(TribbleIndexedFeatureReader.java:226)
    at htsjdk.tribble.TribbleIndexedFeatureReader.<init>(TribbleIndexedFeatureReader.java:92)
    at htsjdk.tribble.TribbleIndexedFeatureReader.<init>(TribbleIndexedFeatureReader.java:103)
    at htsjdk.tribble.AbstractFeatureReader.getFeatureReader(AbstractFeatureReader.java:89)
    at htsjdk.tribble.AbstractFeatureReader.getFeatureReader(AbstractFeatureReader.java:66)
    at htsjdk.variant.vcf.VCFFileReader.<init>(VCFFileReader.java:58)
    at picard.vcf.SortVcf.collectFileReadersAndHeaders(SortVcf.java:111)
    at picard.vcf.SortVcf.doWork(SortVcf.java:95)
    at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:209)
    at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:95)
    at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:105)
Caused by: htsjdk.tribble.TribbleException$InvalidHeader: Your input file has a malformed header: unexpected tag count 6 in line <ID=ENST,Number=.,Type=String,Description="Ensembl transcript identifier",Source="savant",Version="1.1.0">
    at htsjdk.variant.vcf.VCF4Parser.parseLine(VCFHeaderLineTranslator.java:109)
    at htsjdk.variant.vcf.VCFHeaderLineTranslator.parseLine(VCFHeaderLineTranslator.java:51)
    at htsjdk.variant.vcf.VCFCompoundHeaderLine.<init>(VCFCompoundHeaderLine.java:164)
    at htsjdk.variant.vcf.VCFInfoHeaderLine.<init>(VCFInfoHeaderLine.java:48)
    at htsjdk.variant.vcf.AbstractVCFCodec.parseHeaderFromLines(AbstractVCFCodec.java:199)
    at htsjdk.variant.vcf.VCFCodec.readActualHeader(VCFCodec.java:111)
    at htsjdk.tribble.AsciiFeatureCodec.readHeader(AsciiFeatureCodec.java:88)
    at htsjdk.tribble.AsciiFeatureCodec.readHeader(AsciiFeatureCodec.java:41)
    at htsjdk.tribble.TribbleIndexedFeatureReader.readHeader(TribbleIndexedFeatureReader.java:224)
```

From the VCFv4.2 specification:
### 1.2.2 Information field format

INFO fields should be described as follows (first four keys are required, source and version are recommended):

```
##INFO=<ID=ID,Number=number,Type=type,Description="description",Source="source",Version="version">
```

**Comment by cmnbroad** [comment]
Fixed via #https://github.com/samtools/htsjdk/pull/1248.

**Comment by heuermh** [comment]
Thank you!
