### ISSUE TITLE
Copy() and copy constructor in VariantContextBuilder

### ISSUE THREAD

**Issue by lindenb** [samtools/htsjdk#541]
### Subject of the issue

the method copy() ( https://samtools.github.io/htsjdk/javadoc/htsjdk/htsjdk/variant/variantcontext/VariantContextBuilder.html#copy-- ) in `VariantContextBuilder` is not documented and the copy constructor is wrongly implemented if the behavior is to `clone()` the parent.

I found this when I expected to run many variantctxbuild.copy() in my tests to re-use an pre-filled VariantContextBuilder.

```
  public VariantContextBuilder(final VariantContextBuilder parent) {
       this.genotypes =parent.genotypes; // should be cloned
       (...)
       this.attributes(parent.attributes);
       this.filters(parent.filters);
   }    

```
But the 'attributes(Map)' method
- doesn't copy the parent's map ; any change will be affected in the parent
- it  doesn't check that map is immutable
- it  sets attributesCanBeModified=true
        -> and later, any call to attribute(k,v) would raise an UnsupportedOperationException if attribute is still the parent's immutable map

```
java.lang.UnsupportedOperationException
	at java.util.AbstractMap.put(AbstractMap.java:209)
	at htsjdk.variant.variantcontext.VariantContextBuilder.attribute(VariantContextBuilder.java:214)
```

same thing for `this.filters(parent.filters)`

### Steps to reproduce

```
 final VariantContextBuilder root1 = new VariantContextBuilder(snpSource, snpLoc, snpLocStart, snpLocStop, Arrays.asList(Aref, C));
Assert.assertEquals(root1.copy().attribute("x","12345").make().getCommonInfo().getAttributeAsString("x",null),"12345");

```

### Expected behaviour

VariantContextBuilder should clone the paren'ts field

### Actual behaviour

VariantContextBuilder uses its paren'ts pointers

**Comment by tfenne** [comment]
Fixed by #587 (and hardened by #1344). VariantContextBuilder.attributes()/filters() now copy the supplied collection into a fresh mutable map/set, and attribute()/filter() call makeAttributesModifiable()/makeFiltersModifiable() before mutating, so copy() followed by attribute() no longer throws UnsupportedOperationException. Closing as resolved.
