### ISSUE TITLE
nondeterministic failure of RelativeIso8601DateTest.testLazyInstance

### ISSUE THREAD

**Issue by akiezun** [samtools/htsjdk#578]
I had a build fail due to this:

```
   [testng] FAILED: testLazyInstance
   [testng] java.lang.AssertionError: expected [1.46099929E12] but found [1.46099942E12]
   [testng] 	at org.testng.Assert.fail(Assert.java:94)
   [testng] 	at org.testng.Assert.failNotEquals(Assert.java:513)
   [testng] 	at org.testng.Assert.assertEquals(Assert.java:260)
   [testng] 	at org.testng.Assert.assertEquals(Assert.java:273)
   [testng] 	at htsjdk.samtools.util.RelativeIso8601DateTest.testLazyInstance(RelativeIso8601DateTest.java:19)
   [testng] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   [testng] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   [testng] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   [testng] 	at java.lang.reflect.Method.invoke(Method.java:497)
   [testng] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
   [testng] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
   [testng] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
   [testng] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
   [testng] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
   [testng] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
   [testng] 	at org.testng.TestRunner.privateRun(TestRunner.java:782)
   [testng] 	at org.testng.TestRunner.run(TestRunner.java:632)
   [testng] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
   [testng] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
   [testng] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
   [testng] 	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
   [testng] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
   [testng] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
   [testng] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
   [testng] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
   [testng] 	at org.testng.TestNG.run(TestNG.java:1064)
   [testng] 	at org.testng.TestNG.privateMain(TestNG.java:1385)
   [testng] 	at org.testng.TestNG.main(TestNG.java:1354)
```

**Comment by nh13** [comment]
Use this to assert they are equal: http://testng.org/javadocs/org/testng/Assert.html#assertEquals-double-double-double-
