### ISSUE TITLE
SamLocusIterator with missing quality

### ISSUE THREAD

**Issue by dariober** [samtools/htsjdk#611]
Hello- I think there is a bug in SamLocusIterator causing an ArrayIndexOutOfBoundsException when a SAMRecord has the QUAL string missing (i.e. set to "*"). The test case below should reproduce the issue.

I think it can be fixed by editing the method SamLocusIterator.accumulateSamRecord from:

```
if (dontCheckQualities || baseQualities[readOffset] >= minQuality) {
...
```
To:

```
if (baseQualities.length == 0 || dontCheckQualities || baseQualities[readOffset] >= minQuality) {
...
```

I.e. avoiding calling baseQualities[readOffset] on a zero-length array.

This is the test case causing problems:

```
import static org.junit.Assert.*;

import java.io.ByteArrayInputStream;

import org.junit.Test;

import htsjdk.samtools.SamInputResource;
import htsjdk.samtools.SamReader;
import htsjdk.samtools.SamReaderFactory;
import htsjdk.samtools.util.SamLocusIterator;

public class SamLocusIteratorTest {
    private SamReader createSamFileReader(final String samExample) {
        final ByteArrayInputStream inputStream = new ByteArrayInputStream(samExample.getBytes());
        return SamReaderFactory.makeDefault().open(SamInputResource.of(inputStream));
    }

    private SamLocusIterator createSamLocusIterator(final SamReader samReader) {
        final SamLocusIterator ret = new SamLocusIterator(samReader);
        ret.setEmitUncoveredLoci(false);
        return ret;
    }

    @Test
    public void testBasicIterator() {

        final String sqHeader = "@HD\tSO:coordinate\tVN:1.0\n@SQ\tSN:chrM\tAS:HG18\tLN:100000\n";
        final String seq1 = "ACCTACGTTCAATATTACAGGCGAACATACTTACTA";

        final String qual1 = "*"; // Quality string missing!

        final String s1 = "3851612\t16\tchrM\t165\t255\t36M\t*\t0\t0\t" + seq1 + "\t" + qual1 + "\n";
        final String exampleSam = sqHeader + s1 + s1;

        final SamReader samReader = createSamFileReader(exampleSam);
        final SamLocusIterator sli = createSamLocusIterator(samReader);


        // make sure we accumulated depth of 2 for each position
        int pos = 165;
        for (final SamLocusIterator.LocusInfo li : sli) {
            assertEquals(pos++, li.getPosition());
            assertEquals(2, li.getRecordAndPositions().size());
        }

    }
}
```

Stack trace:

```
java.lang.ArrayIndexOutOfBoundsException: 0
	at htsjdk.samtools.util.SamLocusIterator.accumulateSamRecord(SamLocusIterator.java:379)
	at htsjdk.samtools.util.SamLocusIterator.next(SamLocusIterator.java:315)
	at htsjdk.samtools.util.SamLocusIterator.hasNext(SamLocusIterator.java:240)
	at samTextViewer.SamLocusIteratorTest.testBasicIterator(SamLocusIteratorTest.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

```

**Comment by brendanofallon** [comment]
Should be fixed when / if PR #626 is merged

**Comment by magicDGS** [comment]
This could be close, couldn't it?

**Comment by tfenne** [comment]
Fixed by #626 (and #1520). SamLocusIterator.accumulateSamRecord now checks baseQualities.length == 0 before indexing, so records with a missing ("*") QUAL string no longer throw ArrayIndexOutOfBoundsException. Closing as resolved.
