### ISSUE TITLE
EnaRefServiceTest failing in master

### ISSUE THREAD

**Issue by droazen** [samtools/htsjdk#680]
`EnaRefServiceTest` is failing in master with a `GaveUpException`:

```
Gradle suite > Gradle test > htsjdk.samtools.cram.ref.EnaRefServiceTest.test FAILED
    htsjdk.samtools.cram.ref.EnaRefService$GaveUpException
        at htsjdk.samtools.cram.ref.EnaRefService.getSequence(EnaRefService.java:103)
        at htsjdk.samtools.cram.ref.EnaRefService.getSequence(EnaRefService.java:24)
        at htsjdk.samtools.cram.ref.EnaRefServiceTest.test(EnaRefServiceTest.java:12)
```

**Comment by droazen** [comment]
@vadimzalunin can you comment, since this is part of the cram package?

**Comment by vadimzalunin** [comment]
looks like connectivity issue, is it intermittent?

**Comment by lbergelson** [comment]
There were a few days were it was consistently failing but it seems to be back up now.  I think it would be good if the test could identify that the service was unavailable and skip in that case instead of failing.

**Comment by tfenne** [comment]
EnaRefServiceTest is now isolated to the 'ena' test group, which is excluded from the default test runs (build.gradle excludeGroups). It no longer breaks the master build. Closing. (Note: it can still fail in the dedicated ena lane if the service is down, but that no longer affects normal builds.)
