### ISSUE TITLE
Allow CRAM to be read if reference sequences are missing.

### ISSUE THREAD

**Issue by s-andrews** [samtools/htsjdk#719]
I need to parse some CRAM files in an application and currently these are failing with an error "A valid CRAM reference was not supplied..." - which is true - the reference files used to create the original CRAM file aren't available on the system I'm using.

However - all I need from the CRAM files are the mapped positions of the reads.  I don't need the actual sequences so I'd like to be able to read the CRAM files to get at the bits of information I can access without the references.  As far as I can see htsjdk doesn't allow me to do this?

Would it be possible to set the reader up so that assuming a sufficiently lax validation stringency was set that opening a CRAM file with no reference was still possible, and that an exception was thrown only at the point where an API call which would require access to the reference was called?

### Your environment
* version of htsjdk - 2.6.1
* version of java -1.8
* which OS - all

### Steps to reproduce

Use a CRAM file which uses sequence reference paths which are not available:

```
		SamReaderFactory readerFactory = SamReaderFactory.makeDefault().validationStringency(ValidationStringency.SILENT);
		
		SamReader inputSam = readerFactory.open(file); 

		for (SAMRecord samRecord : inputSam) {
                    samRecord.getNotPrimaryAlignmentFlag();
                    samRecord.getMappingQuality();
                    samRecord.getAlignmentStart();
                    samRecord.getAlignmentEnd();
                    samRecord.getReadNegativeStrandFlag();
		}
```

### Expected behaviour
No exception should be triggered because no API call has been made which would require the use of the missing references.

### Actual behaviour
java.lang.IllegalStateException: A valid CRAM reference was not supplied and one cannot be acquired via the property settings reference_fasta or use_cram_ref_download
	at htsjdk.samtools.cram.ref.ReferenceSource.getDefaultCRAMReferenceSource(ReferenceSource.java:108)
	at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:301)
	at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:145)

**Comment by cmnbroad** [comment]
@s-andrews The exception you're hitting is there because the downstream code assumes it has access to the reference, and doesn't fail gracefully without it. I don't see any reliable way to do what you're asking using the current htsjdk implementation.

In general, for CRAM, the smallest unit of access is the "slice", which holds a group of records (in htsjdk the default size is 10,000) that are encoded/decoded together as a unit. So the concept of accessing part of a record, or even an entire single record, doesn't exist. As soon as you retrieve the first record, all of the records in the slice are fully decoded and rehydrated as SAMRecords at once. I think implementing deferred base resolution would require a lot of work, and have a negative performance impact.

**Comment by tfenne** [comment]
@cmnbroad I don't know much about the CRAM implementation in htsjdk, but it sounds like what @s-andrews is asking for is to return records either where the sequence field is just a `*` for "sequence not stored", or perhaps a string where `=` is used for bases that are reference, and just the mismatching bases are present as `A/C/G/T`.  Does CRAM support the encoding of records that have no base string?  If so would it be hard to support a re-hydrate minus base-string mode when the reference is unavailable?

**Comment by s-andrews** [comment]
Yes, what @tfenne suggested is exactly what I'm after.  Dummy records for sequences are fine.  I'd be happy to fake up a polyN genome sequence and get gibberish back as I don't need the sequence at all and it seems a waste to make people locate and download the references when they're not actually going to be used other than to get past the initial verification.

**Comment by cmnbroad** [comment]
I see. It might be possible to do something like that.

@s-andrews Short of such a thing being implemented, you can provide a referenceSource to the SAMReaderFactory in the form of an implementation of the htsjdk.samtools.cram.ref.CRAMReferenceSource interface, which is a pretty small interface that just returns the reference bases for a given sequence. As of 2.6.1, the calling code will require the md5 digest of the bases returned to match those used to create the CRAM, but previous versions do not. So if you revert to pre 2.6.1 htsjdk, you might be able to read your crams by providing a (sufficiently long) polyN sequence as you suggest. Haven't tried such a thing myself though.

**Comment by dbolser-ebi** [comment]
I have a related issue (I think) where I want to disable the MD5SUM check under certain circumstances. I realize this seems dangerous, but in this case there are ~1G reference sequences, and I can verify the MD5SUM of the whole genome (we have ~1k CRAMs from this genome to process). Could this be an option for me as well as a useful feature here?

**Comment by tfenne** [comment]
Checked this against current master -- still reproduces, so leaving open.

Wrote a normal reference-compressed CRAM, deleted the reference fasta and its .fai, then tried to read it:

```
IllegalArgumentException: A reference must be supplied that includes the reference sequence for 1.
```

Worth noting for anyone triaging: `CRAMReferencelessTest.testReadCRAMNoReferenceRequired` exists and passes, but it covers a different thing -- a CRAM written with reference compression disabled (RR=false), i.e. a file that never needed a reference. It does not cover this request, which is reading a reference-compressed CRAM when the reference is unavailable and only accessing the fields (alignment positions, flags) that do not require it.
