### ISSUE TITLE
non-deterministic test failure in AsyncBufferedIteratorTest

### ISSUE THREAD

**Issue by lbergelson** [samtools/htsjdk#776]
I'm seeing a random failure of AsynchBufferedIteratorTest.testBackground blocks.  

```
htsjdk.samtools.util.AsyncBufferedIteratorTest.testBackgroundBlocks FAILED
    java.lang.AssertionError: expected [9] but found [0]
        at org.testng.Assert.fail(Assert.java:94)
        at org.testng.Assert.failNotEquals(Assert.java:496)
        at org.testng.Assert.assertEquals(Assert.java:125)
        at org.testng.Assert.assertEquals(Assert.java:372)
        at org.testng.Assert.assertEquals(Assert.java:382)
        at htsjdk.samtools.util.AsyncBufferedIteratorTest.testBackgroundBlocks(AsyncBufferedIteratorTest.java:79)
```

The test has a comment saying that it's subject to race conditions.  

```
  Thread.sleep(10); // how do we write this test and not be subject to race conditions?
        // should have read 9 records: 2*3 in the buffers, and another 3 read but
        // blocking waiting to be added 
```

**Comment by tfenne** [comment]
Mitigated by #790 (2.10.0), which replaced the fixed sleep with a poll; no failures reported since.
