### ISSUE TITLE
htsjdk.tribble.TribbleException: The provided VCF file is malformed at approximately line number 3793131: unparsable vcf record with allele 0

### ISSUE THREAD

**Issue by mmokrejs** [samtools/htsjdk#788]
Hi,
  can you please tell us what are the zeroes on the problematic lines? Is that an ENSEML-86 issue of htsjdk issue? Ideally please update original https://github.com/igvteam/igv/issues/362 issue.

```
java -Djavaio.tmpdir=. -Xmx93g -jar /scratch/mmokrejs/IGVTools_2.3.89/igvtools.jar index /scratch/mmokrejs/db/ftp.ensembl.org/pub/release-86/variation/vcf/homo_sapiens/CSHL-HAPMAP-HapMap-CEU.vcf
ERROR [2017-01-20 23:30:23,817]  [IgvTools.java:264] [main]  htsjdk.tribble.TribbleException: The provided VCF file is malformed at approximately line number 3793131: unparsable vcf record with allele 0
java.lang.RuntimeException: htsjdk.tribble.TribbleException: The provided VCF file is malformed at approximately line number 3793131: unparsable vcf record with allele 0
        at org.broad.igv.tools.IgvTools.doIndex(IgvTools.java:998)
        at org.broad.igv.tools.IgvTools.run(IgvTools.java:393)
        at org.broad.igv.tools.IgvTools.main(IgvTools.java:259)
Caused by: htsjdk.tribble.TribbleException: The provided VCF file is malformed at approximately line number 3793131: unparsable vcf record with allele 0
        at htsjdk.variant.vcf.AbstractVCFCodec.generateException(AbstractVCFCodec.java:784)
        at htsjdk.variant.vcf.AbstractVCFCodec.checkAllele(AbstractVCFCodec.java:569)
        at htsjdk.variant.vcf.AbstractVCFCodec.parseSingleAltAllele(AbstractVCFCodec.java:609)
        at htsjdk.variant.vcf.AbstractVCFCodec.parseAlleles(AbstractVCFCodec.java:539)
        at htsjdk.variant.vcf.AbstractVCFCodec.parseVCFLine(AbstractVCFCodec.java:336)
        at htsjdk.variant.vcf.AbstractVCFCodec.decodeLine(AbstractVCFCodec.java:279)
        at htsjdk.variant.vcf.AbstractVCFCodec.decode(AbstractVCFCodec.java:257)
        at htsjdk.variant.vcf.AbstractVCFCodec.decode(AbstractVCFCodec.java:60)
        at htsjdk.tribble.AsciiFeatureCodec.decode(AsciiFeatureCodec.java:79)
        at htsjdk.tribble.AsciiFeatureCodec.decode(AsciiFeatureCodec.java:41)
        at htsjdk.tribble.AbstractFeatureCodec.decodeLoc(AbstractFeatureCodec.java:43)
        at org.broad.igv.feature.tribble.VCFWrapperCodec.decodeLoc(VCFWrapperCodec.java:58)
        at org.broad.igv.feature.tribble.VCFWrapperCodec.decodeLoc(VCFWrapperCodec.java:43)
        at htsjdk.tribble.index.IndexFactory$FeatureIterator.readNextFeature(IndexFactory.java:502)
        at htsjdk.tribble.index.IndexFactory$FeatureIterator.next(IndexFactory.java:464)
        at htsjdk.tribble.index.IndexFactory.createIndex(IndexFactory.java:338)
        at htsjdk.tribble.index.IndexFactory.createLinearIndex(IndexFactory.java:223)
        at org.broad.igv.tools.IgvTools.createTribbleIndex(IgvTools.java:1062)
        at org.broad.igv.tools.IgvTools.doIndex(IgvTools.java:981)
```

```
3793131 X       2782116 rs5939319       G       A,0     .       .       dbSNP_147;TSA=SNV;E_Freq;E_Hapmap;E_1000G;E_ESP;E_ExAC;AF=0.0833333,0.25
3793132 X       2785350 rs1486175       T       0,C     .       .       dbSNP_147;TSA=SNV;E_Freq;E_Hapmap;E_1000G;AF=0.254237,0.5
3793133 X       2785592 rs1419931       A       0,G     .       .       dbSNP_147;TSA=SNV;E_Freq;E_Hapmap;E_1000G;AF=0.25,0.491667
3
```

**Comment by lbergelson** [comment]
@mmokrejs That definitely looks like a malformed vcf to me.  `0` is not a valid allele string. Any combination of 'ACGT` or named symbolic alleles like `<LONG_DEL_32>` is valid.  

What is 0 meant to represent?

**Comment by lbergelson** [comment]
Is it meant to be a spanning deletion?

**Comment by mmokrejs** [comment]
@lbergelson I do not know.  The file path includes the original URL. Would you mind asking ENSEMBL developers directly?

**Comment by vdauwera** [comment]
@mmokrejs The htsjdk validator is correct, this file is invalid according to the VCF specification. There's really not anything we can do about it, regardless of what those zeroes are supposed to represent... Whoever is interested in consuming this file should notify its creator that is is not a valid VCF.

**Comment by hesparrow** [comment]
Ensembl are aware of this bug, and it is fixed for our upcoming release. Apologies for this inconvenience.

**Comment by lbergelson** [comment]
@hesparrow Thanks for chiming in!  👍  Going to close this.
