### ISSUE TITLE
MarkDuplicates requires sorted input although docs say it does not

### ISSUE THREAD

**Issue by mmokrejs** [samtools/htsjdk#792]
Hi,
  unless I misread the runtime help by default MarkDuplicates anticipates unsorted input and from that I infer it is supported. I did not fiddle with any of the below defaults on my commandline as it seemed I can stay on the safe side with them.

```
ASSUME_SORTED=Boolean
AS=Boolean                    If true, assume that the input file is coordinate sorted even if the header says 
                              otherwise. Deprecated, used ASSUME_SORT_ORDER=coordinate instead.  Default value: false. 
                              This option can be set to 'null' to clear the default value. Possible values: {true, 
                              false}  Cannot be used in conjuction with option(s) ASSUME_SORT_ORDER (ASO)

ASSUME_SORT_ORDER=SortOrder
ASO=SortOrder                 If not null, assume that the input file has this order even if the header says otherwise.  
                              Default value: null. Possible values: {unsorted, queryname, coordinate, duplicate}  
                              Cannot be used in conjuction with option(s) ASSUME_SORTED (AS)
```

However, after quite some CPU cycles picard bailed out that my iinput was not sorted. A bit too late, IMHO. I suggest at least updating the docs.

```
INFO    2017-01-29 23:24:40     MarkDuplicates  After buildSortedReadEndLists freeMemory: 17464432592; totalMemory: 29387390976; maxMemory: 46767538176
INFO    2017-01-29 23:24:40     MarkDuplicates  Will retain up to 1461485568 duplicate indices before spilling to disk.
INFO    2017-01-29 23:24:41     MarkDuplicates  Traversing read pair information and detecting duplicates.
INFO    2017-01-29 23:24:48     MarkDuplicates  Traversing fragment information and detecting duplicates.
INFO    2017-01-29 23:25:00     MarkDuplicates  Sorting list of duplicate records.
INFO    2017-01-29 23:25:11     MarkDuplicates  After generateDuplicateIndexes freeMemory: 28261857208; totalMemory: 40271609856; maxMemory: 46767538176
INFO    2017-01-29 23:25:11     MarkDuplicates  Marking 120403 records as duplicates.
INFO    2017-01-29 23:25:11     MarkDuplicates  Found 22 optical duplicate clusters.
INFO    2017-01-29 23:25:11     MarkDuplicates  Reads are assumed to be ordered by: unsorted
[Sun Jan 29 23:25:11 CET 2017] picard.sam.markduplicates.MarkDuplicates done. Elapsed time: 20.88 minutes.
Runtime.totalMemory()=40271609856
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" picard.PicardException: This program requires input that are either coordinate or query sorted. Found unsorted
        at picard.sam.markduplicates.MarkDuplicates.doWork(MarkDuplicates.java:244)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:205)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:94)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:104)
```

**Comment by yfarjoun** [comment]
I agree that this is confusing and possibly not documented properly. There are two ways to run MarkDuplicates in picard:

1. with a coordinate sorted bam (only mark "canonical" records, not secondary or supplementary)
2. with a queryname sorted bam (mark all the reads, secondary and supplementary reads are marked like their canonical read)

(this is true regardless of what is written in the header...the file must be in one of these two orders)

Unfortunately the program only detects problems when outputting as the writer is expecting a certain order and will blowup if that order isn't actually observed.

I hope this helps.

This would be better on the forum...

**Comment by vdauwera** [comment]
If the documentation is lacking then we should fix it. We'll add the points discussed above; this issue should remain open until that is done.

**Comment by tfenne** [comment]
This should be in Picard and not HTSJSK.
