### ISSUE TITLE
Error executing two sequential SamReader.queryOverlapping() calls for a CRAM File

### ISSUE THREAD

**Issue by skashin** [samtools/htsjdk#918]
When I run the code below

Path path = Paths.get(newURI(cramFile));
SamReader reader = factory.open(path);
CloseableIterator<SAMRecord> iterator = reader.queryOverlapping("chr20”, 1000000, 1010000);
iterator.close();
iterator = reader.queryOverlapping("chr2", 1,10000);

I get the following exception:
htsjdk.samtools.util.RuntimeEOFException: java.nio.channels.ClosedChannelException
	at htsjdk.samtools.CRAMFileReader$CRAMIntervalIterator.<init>(CRAMFileReader.java:490)
	at htsjdk.samtools.CRAMFileReader.query(CRAMFileReader.java:455)
	at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:528)
	at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:533)
	at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.queryOverlapping(SamReader.java:395)
	at htsjdk.samtools.GoogleTest.queryCram(GoogleTest.java:127)
	at htsjdk.samtools.GoogleTest.main(GoogleTest.java:24)

This exception occurs because CRAMIterator closes the input stream that was passed to it in the constructor.

Wouldn’t it be cleaner to make CRAMFileReader responsible for closing the input stream, regardless of how it was constructed?

Thanks

**Comment by cmnbroad** [comment]
Yes, the CRAMIterator code wraps the input stream with a CountingInputStream, and then closes it when the iterator is closed, which results in the original underlying stream being closed. That should be suppressed.

**Comment by tfenne** [comment]
Fixed by #1533 (merged 2021). CRAMFileReader no longer lets closeable iterators close the underlying stream, so sequential queryOverlapping() calls work; regression tests are in CRAMIndexQueryTest. Closing as resolved.
