### ISSUE TITLE
htsjdk.variant.bcf2.BCF2Utils.determineIntegerType(List<Integer> ) with '.' value raises a NPE

### ISSUE THREAD

**Issue by lindenb** [samtools/htsjdk#961]
### Subject of the issue

I don't know if it's a problem with my annotation that would not follow the vcf spec or a problem with the BCF encoder. I've got the following header:

`##INFO=<ID=MYATT,Number=A,Type=Integer>`

and in my variant there is a '.' in my list of integer:

`MYATT=.,0;`

it's ok if I save as VCF, but when trying to save this as BCF, this raises the following NPE:

```


java.lang.NullPointerException
	at htsjdk.variant.bcf2.BCF2Utils.determineIntegerType(BCF2Utils.java:255)
	at htsjdk.variant.variantcontext.writer.BCF2FieldEncoder$GenericInts.getDynamicType(BCF2FieldEncoder.java:440)
	at htsjdk.variant.variantcontext.writer.BCF2FieldEncoder.getType(BCF2FieldEncoder.java:217)
	at htsjdk.variant.variantcontext.writer.BCF2FieldWriter$GenericSiteWriter.site(BCF2FieldWriter.java:95)
	at htsjdk.variant.variantcontext.writer.BCF2Writer.buildInfo(BCF2Writer.java:353)
	at htsjdk.variant.variantcontext.writer.BCF2Writer.buildSitesData(BCF2Writer.java:269)
	at htsjdk.variant.variantcontext.writer.BCF2Writer.add(BCF2Writer.java:202)
(....)

```
with htsjdk.variant.bcf2.BCF2Utils.determineIntegerType :

`for ( final int value : values ) {`

### Your environment
* version of htsjdk 2.9.1
* version of java 1.8

**Comment by yfarjoun** [comment]
The test suite ignores the BCF extension due to  "header is not properly
constructed"...I am able to reproduce your error and am thus investigating
a little...Thanks.

**Comment by yfarjoun** [comment]
Reading the BCF2 code it seems that nulls are skipped and pruned..but this seems to be a bad thing to do, as it will change the index of the non-null elements. This is done quite systematically.

Example code:

encode (//commented arrows indicate place where null values are treated differently):
```java
     @Override
        public void encodeValue(final BCF2Encoder encoder, final Object value, final BCF2Type type, final int minValues) throws IOException {
            int count = 0;
            if ( value != null ) { /// <<<<<<=========
                encoder.encodeRawInt((Integer)value, type);
                count++;
            }
            for ( ; count < minValues; count++ ) encoder.encodeRawMissingValue(type);
        }
 ```

decode:
```java
 public final Object decodeTypedValue(final byte typeDescriptor, final int size) throws IOException {
        if ( size == 0 ) {
            // missing value => null in java
            return null;
        } else {
            final BCF2Type type = BCF2Utils.decodeType(typeDescriptor);
            if ( type == BCF2Type.CHAR ) { // special case string decoding for efficiency
                return decodeLiteralString(size);
            } else if ( size == 1 ) {
                return decodeSingleValue(type);
            } else {
                final ArrayList<Object> ints = new ArrayList<Object>(size);
                for ( int i = 0; i < size; i++ ) {
                    final Object val = decodeSingleValue(type);
                    if ( val == null ) continue; // auto-pruning.  We remove trailing nulls <<<<<<========
                    ints.add(val);
                }
                return ints.isEmpty() ? null : ints; // return null when all of the values are null
            }
        }
    }
```

This causes lists that contain nulls to be modified by the encoder which seems like a really bad idea. for example, the list ".,1" (after changing the code that causes the NPE) gives back a list of size 1, which then fails the comparison.

I'd like to change this so that we store nulls in their right place...but I wanted to know if there's a reason why we do not... 

Summoning some long-timers: @tfenne @alecw thanks.

**Comment by yfarjoun** [comment]
I think I found the real culprit...BCF2 format doesn't allow vectors with missing values:

From VCFv4.3.pdf section 6.3.3 "Vectors of mixed length":
>   Note that this means that it’s illegal to encode a vector VCF field with missing values; the BCF2 codec should signal an error in this case. 

Which explains why missing values are omitted (though it means that htsjdk should be throwing
an exception when a vector has a missing value...)

So basically BCF format is borked when it comes to missing values. If you want this changed, this needs to happen via hts-specs first.

Sorry.

**Comment by lindenb** [comment]
> So basically BCF format is borked when it comes to missing values. If you want this changed, this needs to happen via hts-specs first.

@yfarjoun  thanks for checking this. 

> though it means that htsjdk should be throwing an exception when a vector has a missing value...

yes please ! :-)

**Comment by yfarjoun** [comment]
Reopening, because I jumped to conclusions to quickly 😲  

there is a way to encode vectors with missing data in them, but perhaps it isn't used in the code pathway that I'm examining...investigating.

**Comment by alecw** [comment]
Sorry, @yfarjoun , I worked with the VCF code very little.

**Comment by tfenne** [comment]
Fixed on master for the upcoming 6.0.0: the BCF writer encodes a missing element of an integer list as the BCF missing value instead of throwing (#1828), and the reader keeps it as a null in the same position (#1827).
