### ISSUE TITLE
VCFFileReader.fromVCF throws an NPE when input contains no CONTIG lines

### ISSUE THREAD

**Issue by cmnbroad** [samtools/htsjdk#978]
You can see this using Picard VcfToIntervalList, which just calls fromVCF, on this vcf:

##fileformat=VCFv4.2
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
1       100     a       G       A       232.46  PASS    .

More generally, SamFileHeader.getSequence, which is where the NPE originates, should probably handle a null sequence dictionary better and throw something more specific.

Stack (from the GATK version of VcfToIntervalList):
  java.lang.Thread.State: RUNNABLE
	  at htsjdk.samtools.SAMFileHeader.getSequence(SAMFileHeader.java:153)
	  at htsjdk.samtools.util.IntervalList.add(IntervalList.java:93)
	  at htsjdk.variant.vcf.VCFFileReader.fromVcf(VCFFileReader.java:119)
	  at htsjdk.variant.vcf.VCFFileReader.fromVcf(VCFFileReader.java:88)
	  at org.broadinstitute.hellbender.tools.picard.vcf.VcfToIntervalList.doWork(VcfToIntervalList.java:51)

**Comment by cmnbroad** [comment]
Fixed via #988.
